name: My CICD pipeline in Github Actions

on: 
 push: 
  branches: main

jobs:
  build:
   runs-on: ubuntu-latest

   steps: 
    -  uses: actions/checkout@v4   

    -  name: My first step
       run: |
         echo "This is a Devops"
         uname -a
       
    -  name: Check the docker installation
       run: |
         docker
         docker images

    -  name: Run Docker Container 
       run: |
         docker run hello-world
         
